RDKBACCL-1885 : observing BPI build issue in tip code of onewifi (#1212)
Reason for change: Observing below errors,
../../../git/source/webconfig/wifi_ovsdb_translator.c:3075:98: error: 'struct schema_Wifi_VIF_State' has no member named 'mld_if_name'; did you mean 'if_name'?       |  3075 |         if (get_mlo_vap_name_from_per_radio(vap->vap_name, vap_row->mld_if_name, sizeof(vap_row->mld_if_name))) {
Test Procedure: BPI build successful
Risks: None

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>
(cherry picked from commit bca9e267cdc85f1cbc4fecd8a64ad09b4ba99337)