RDKBACCL-839 : Removed onewifi db for EasyMesh enabled build (#406)
Reason for change: Addressed below build time and run-time issues.
undefined reference to `get_wifi_radio_config'
undefined reference to `get_wifi_vap_config'
undefined symbol: wifidb_get_rfc_config
undefined symbol: wifidb_init_interworking_config_default
undefined reference to 'get_all_param_from_psm_and_set_into_db'
Test procedure: Onewifi process is up and running and db also not
created at /opt/secure/wifi path
Risks: None

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>
Cherrypicked from commit c958e9def3d732bdd4b7d138f444f8a438d6c1c8