RDKBACCL-703 : Observing onewifi build errors if we enabled easymesh related flags
Reason for change:  Below are the errors,
ld: ../../source/apps/OneWifi-wifi_apps.o:(.data.app_desc+0x380): undefined reference to `em_init'
ld: ../../source/apps/OneWifi-wifi_apps.o:(.data.app_desc+0x388): undefined reference to `em_event'
ld: ../../source/apps/OneWifi-wifi_apps.o:(.data.app_desc+0x390): undefined reference to `em_deinit'
Test Procedure: Able to compile onewifi without build errors
Risks: Low

Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>
Cherrypicked from commit 7c239b3fa81537173d726733868883cf79466337